name: Python Cache Example
on:
  schedule:
    - cron: '0 1,5,9,13,17,21 * * *'
      
  # 手动运行
  workflow_dispatch:
env:
  clientId: 10101001-0100-0011-0101-100000000001
  tenant: mylives01.onmicrosoft.com
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # 安装依赖并创建虚拟环境
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      # 将当前目录添加到PYTHONPATH
      - name: Add current directory to PYTHONPATH
        run: |
          echo "export PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          
      # 如果之前已经有了缓存，则从缓存中还原
      - name: Restore cache if available
        id: restore_cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: python-${{ hashFiles('requirements.txt') }}
      
      # 安装所需的包
      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Install pip install --upgrade pip
        run: pip install --upgrade pip
        
      # 运行测试等其他任务...
      - name: Run itv
        run: python ${{ github.workspace }}/itv.py

      - name: Run cctv
        run: python ${{ github.workspace }}/cctv.py
          
      - name: Run weishi
        run: python ${{ github.workspace }}/weishi.py
          
      - name: Run ktpd
        run: python ${{ github.workspace }}/ktpd.py
          
      - name: Run ysyl
        run: python ${{ github.workspace }}/ysyl.py
             
      - name: Run qita
        run: python ${{ github.workspace }}/qita.py
      - name: 提交总表更改
        run: |
          git config --local user.name "GBOXDEO" 
          git config --local user.email "g832@qq.com"
          git add .
          git commit *.txt -m "Add generated file"
          git push -f
        
