name: MIPTV

on: [push]

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install selenium requests futures eventlet
      - name: Run itv
        run: python ${{ github.workspace }}/itv.py
      - name: Run itvtest
        run: python ${{ github.workspace }}/itvtest.py
      - name: 提交更改
        run: |
          git config --local user.email "g832@qq.com"
          git config --local user.name "GBOXDEO"
          git add .
          git commit *.txt -m "Add generated file"
          #git pull --rebase
          git push -f
