name: Python Cache Example
on:
  schedule:
    - cron: '0 3,7,11,15,19,23 * * *'
      
  # 手动运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      # 运行测试等其他任务...
      - name: Run itv
        run: |
          python ${{ github.workspace }}/itv.py
          python ${{ github.workspace }}/cctv.py
          python ${{ github.workspace }}/weishi.py
          python ${{ github.workspace }}/ktpd.py
          python ${{ github.workspace }}/ysyl.py
          python ${{ github.workspace }}/qita.py

      - name: 提交总表更改
        run: |
          git config --local user.name "GBOXDEO" 
          git config --local user.email "g832@qq.com"
          git add .
          git commit *.txt -m "Add generated file"
          git push -f
