name: itvlist

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run itv_test
        run: python ${{ github.workspace }}/itv_test.py

      - name: Run cctv
        run: python ${{ github.workspace }}/cctv.py
        
      - name: Run weishi
        run: python ${{ github.workspace }}/weishi.py

      - name: Run ktpd
        run: python ${{ github.workspace }}/ktpd.py

      - name: Run ysyl
        run: python ${{ github.workspace }}/ysyl.py

      - name: Run xiangang
        run: python ${{ github.workspace }}/xiangang.py
        
      - name: Run qita
        run: python ${{ github.workspace }}/qita.py
        
      - name: 提交更改
        run: |
          git config --local user.email "g832@qq.com"
          git config --local user.name "GBOXDEO"
          git add .
          git commit *.txt -m "Add generated file"
          #git pull --rebase
          git push -f
