# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # 安装所需的包
    - name: Install dependencies
      run: pip install selenium requests futures eventlet
        
      # 运行测试等其他任务...
    - name: Run itv
      run: python ${{ github.workspace }}/itv.py
    - name: 提交更改
      run: |
        git config --local user.name "GBOXDEO" 
        git config --local user.email "g832@qq.com"
        git add .
        git commit itv.txt -m "Add generated file"
        git push -f
    - name: Run cctv
      run: python ${{ github.workspace }}/cctv.py
    - name: 提交cctv更改
      run: |
        git add .
        git commit cctv.txt -m "Add generated file"
        git push -f
          
    - name: Run weishi
      run: python ${{ github.workspace }}/weishi.py
    - name: 提交weishi更改
      run: |
        git add .
        git commit weishi.txt -m "Add generated file"
        git push -f
          
    - name: Run ktpd
      run: python ${{ github.workspace }}/ktpd.py
    - name: 提交ktpd更改
      run: |
        git add .
        git commit ktpd.txt -m "Add generated file"
        git push -f
          
    - name: Run ysyl
      run: python ${{ github.workspace }}/ysyl.py
    - name: 提交ysyl更改
      run: |
        git add .
        git commit ysyl.txt -m "Add generated file"
        git push -f
             
    - name: Run qita
      run: python ${{ github.workspace }}/qita.py
    - name: 提交总表更改
      run: |
        git add .
        git commit qita.txt -m "Add generated file"
        git commit itvlist.txt -m "Add generated file"
        git push -f
          
      # 保存新的缓存
    - name: Save cache for future use
      if: steps.restore_cache.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: python-${{ hashFiles('requirements.txt') }}
